#!/bin/bash

prefix="/peb/php7115"

pid_file="$prefix/var/run/php-fpm.pid"

if [ -f "$pid_file" ] ; then
    fpm_pid=`cat "$pid_file"`
fi

php_fpm=`ps -e -o user,pid,ppid,comm,args | grep 'root.*php\-fpm.*master'`

start_fpm(){
    if [ -z "$php_fpm" ] ; then
        echo 'starting php-fpm...'
        sudo $prefix/sbin/php-fpm
    else
        echo 'php-fpm already running'
    fi
}

stop_fpm(){
    if [ -n "$fpm_pid" ] && [ -n "$php_fpm" ] ; then
        echo 'stopping php-fpm...'
        sudo kill $fpm_pid
    else
        echo 'php-fpm not running'
    fi
}

case $1 in
    'start')
        start_fpm
    ;;
    'stop')
        stop_fpm
    ;;
    'restart')
        if [ -n "$php_fpm" ] ; then
            stop_fpm
            while [ -n "$php_fpm" ] ; do
                sleep 1
                php_fpm=`ps -e -o user,comm,args | grep 'root.*php\-fpm.*master'`
            done
        fi
        start_fpm
    ;;
    *)
        echo "usage fpm [start|stop|restart]"
    ;;
esac

